"""initial schema

Revision ID: 938d5bd6c630
Revises: 
Create Date: 2026-06-10 01:28:52.113153
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import idmas.infrastructure.db.models   # GUID 自定义类型

revision = '938d5bd6c630'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_tasks',
    sa.Column('id', idmas.infrastructure.db.models.GUID(), nullable=False),
    sa.Column('drawing_id', idmas.infrastructure.db.models.GUID(), nullable=False),
    sa.Column('user_id', idmas.infrastructure.db.models.GUID(), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('prompt_mode', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('background', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('langgraph_thread_id', sa.String(length=64), nullable=True),
    sa.Column('vision_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('ocr_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('design_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('process_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('knowledge_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('report_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('conflicts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('debate_rounds', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('human_decision', sa.Text(), nullable=True),
    sa.Column('inference_time_ms', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_tasks_drawing_id'), 'analysis_tasks', ['drawing_id'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_status'), 'analysis_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_user_id'), 'analysis_tasks', ['user_id'], unique=False)
    op.create_table('drawing_labels',
    sa.Column('id', idmas.infrastructure.db.models.GUID(), nullable=False),
    sa.Column('drawing_id', idmas.infrastructure.db.models.GUID(), nullable=False),
    sa.Column('label_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bounding_box', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('spatial_info', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawing_labels_drawing_id'), 'drawing_labels', ['drawing_id'], unique=False)
    op.create_table('drawings',
    sa.Column('id', idmas.infrastructure.db.models.GUID(), nullable=False),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_doc_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('drawing_type', sa.String(length=32), nullable=False),
    sa.Column('file_format', sa.String(length=16), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=16), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', idmas.infrastructure.db.models.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawings_created_by'), 'drawings', ['created_by'], unique=False)
    op.create_index(op.f('ix_drawings_drawing_type'), 'drawings', ['drawing_type'], unique=False)
    op.create_index(op.f('ix_drawings_title'), 'drawings', ['title'], unique=False)
    op.create_table('review_records',
    sa.Column('id', idmas.infrastructure.db.models.GUID(), nullable=False),
    sa.Column('task_id', idmas.infrastructure.db.models.GUID(), nullable=False),
    sa.Column('reviewer_id', idmas.infrastructure.db.models.GUID(), nullable=False),
    sa.Column('label_id', sa.String(length=32), nullable=False),
    sa.Column('original_name', sa.String(length=256), nullable=False),
    sa.Column('corrected_name', sa.String(length=256), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('feedback_status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_records_task_id'), 'review_records', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_records_task_id'), table_name='review_records')
    op.drop_table('review_records')
    op.drop_index(op.f('ix_drawings_title'), table_name='drawings')
    op.drop_index(op.f('ix_drawings_drawing_type'), table_name='drawings')
    op.drop_index(op.f('ix_drawings_created_by'), table_name='drawings')
    op.drop_table('drawings')
    op.drop_index(op.f('ix_drawing_labels_drawing_id'), table_name='drawing_labels')
    op.drop_table('drawing_labels')
    op.drop_index(op.f('ix_analysis_tasks_user_id'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_status'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_drawing_id'), table_name='analysis_tasks')
    op.drop_table('analysis_tasks')
    # ### end Alembic commands ###
